const record = [
  [
      {
        "Fujita" : {
        PA: 4,
        atBat: 4,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 1,
        clutchHit: 1,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
        }
      },
      {
          "AAA" : {
          PA: 5,
          atBat: 4,
          single: 0,
          double: 0,
          triple: 0,
          HR: 0,
          RBI: 0,
          clutchHit: 0,
          sucrificeBunt: 0,
          sucrificeFly: 0,
          SB: 0,
          BB: 1,
          K: 2,
          }  
      },
      {
          "BBB" : {
          PA: 4,
          atBat: 4,
          single: 2,
          double: 0,
          triple: 0,
          HR: 0,
          RBI: 0,
          clutchHit: 0,
          sucrificeBunt: 0,
          sucrificefly: 0,
          SB: 2,
          BB: 0,
          K: 0,
          }
      },
  ],
  [
      {
          "Fujita": {
          PA: 4,
          atBat: 3,
          single: 0,
          double: 0,
          triple: 0,
          HR: 0,
          RBI: 0,
          clutcchHit: 0,
          sucrificeBunt: 0,
          sucrificefly: 0,
          SB: 1,
          BB: 1,
          K: 1,
          }
      },
      {
          Name: "AAA",
          PA: 4,
          atBat: 4,
          single: 1,
          double: 0,
          triple: 0,
          HR: 0,
          RBI: 1,
          clutchHit: 1,
          sucrificeBunt: 0,
          sucrificeFly: 0,
          SB: 0,
          BB: 0,
          K: 1,
      },
  
      {
          Name: "BBB",
          PA: 4,
          atBat: 4,
          single: 1,
          double: 0,
          triple: 0,
          HR: 0,
          RBI: 1,
          clutcchHit: 1,
          sucrificeBunt: 0,
          sucrificefly: 0,
          SB: 0,
          BB: 0,
          K: 1,
      },
  ],
  [
      {
          "Fujita": {
          PA: 4,
          atBat: 4,
          single: 1,
          double: 0,
          triple: 0,
          HR: 0,
          RBI: 1,
          clutchHit: 1,
          sucrificeBunt: 0,
          sucrificefly: 0,
          SB: 0,
          BB: 0,
          K: 1,
          }
      },
      {
          Name: "AAA",
          PA: 4,
          atBat: 4,
          single: 1,
          double: 0,
          triple: 0,
          HR: 0,
          RBI: 1,
          clutchHit: 1,
          sucrificeBunt: 0,
          sucrificeFly: 0,
          SB: 0,
          BB: 0,
          K: 1,
  
      },
      {
          Name: "BBB",
          PA: 4,
          atBat: 4,
          single: 1,
          double: 0,
          triple: 0,
          HR: 0,
          RBI: 1,
          clutchHit: 1,
          sucrificeBunt: 0,
          sucrificefly: 0,
          SB: 0,
          BB: 0,
          K: 1,
      },
  ]
  ];

