const record = [
  [
      {
        "AAAAA" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
        }
      },
      {
        "BBBBB" : {
        PA: 3,
        atBat: 1,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 3,
        BB: 2,
        K: 2,
        }  
      },
      {
        "CCCCC" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
        }
      },
      {
        "DDDDD" : {
        PA: 2,
        atBat: 1,
        single: 2,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 0,
        }
    },
    {
        "EEEEE" : {
        PA: 2,
        atBat: 2,
        single: 2,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 2,
        }
    },
    {
        "FFFFF" : {
        PA: 2,
        atBat: 0,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 2,
        K: 0,
        }
    },
    {
        "GGGGG" : {
        PA: 2,
        atBat: 2,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 1,
        BB: 0,
        K: 0,
        }
    },
    {
        "HHHHH" : {
        PA: 3,
        atBat: 3,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 1,
        clutchHit: 1,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
        }
    },
    {
        "IIIII" : {
        PA: 3,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
        }
    },
    {
        "JJJJJ" : {
        PA: 2,
        atBat: 1,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
        }
    },
  ],
  [
    {
        "AAAAA" : {
        PA: 3,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 2,
        }
    },
    {
        "BBBBB" : {
        PA: 3,
        atBat: 3,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 1,
        BB: 0,
        K: 0,
        }  
    },
    {
        "CCCCC" : {
        PA: 3,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 2,
        K: 1,
        }
    },
    {
        "DDDDD" : {
        PA: 3,
        atBat: 3,
        single: 0,
        double: 1,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
        }
    },
    {
        "EEEEE" : {
        PA: 3,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 0,
        }
    },
    {
        "FFFFF" : {
        PA: 3,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
        }
    },
    {
        "GGGGG" : {
        PA: 3,
        atBat: 2,
        single: 2,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 2,
        }
    },
    {
        "HHHHH" : {
        PA: 3,
        atBat: 3,
        single: 0,
        double: 1,
        triple: 0,
        HR: 0,
        RBI: 1,
        clutchHit: 1,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
        }
    },
    { 
        "IIIII" : {
        PA: 3,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
        }
    },
    {
        "JJJJJ" : {
        PA: 2,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 1,
        }
    },
  ],
  [
    {
        "AAAAA" : {
        PA: 2,
        atBat: 2,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
        }
    },
    {
        "BBBBB" : {
        PA: 2,
        atBat: 2,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 1,
        BB: 0,
        K: 0,
        }  
    },
    {
        "CCCCC" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 2,
        }
    },
    {
        "DDDDD" : {
        PA: 2,
        atBat: 0,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
        }
    },
    {
        "EEEEE" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
        }
    },
    {
        "FFFFF" : {
        PA: 2,
        atBat: 2,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
        }
    },
    {
        "GGGGG" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 1,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
        }
    },
    {
        "HHHHH" : {
        PA: 3,
        atBat: 0,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
        }
    },
    {
        "IIIII" : {
        PA: 2,
        atBat: 2,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
        }
    },
    {
        "JJJJJ" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
        }
    },
],
]
